### ISSUE TITLE
nxn othello

### ISSUE THREAD

**Issue by LeoDog896** [LimeEng/magpie#58]
Hi!

I was interested in using this library for a [general-purpose combinatorial game solver](https://github.com/leoDog896/game-solver), and I was wondering if you were open to pull requests for non-standard board sizes.

**Comment by LimeEng** [comment]
Hello! I completely missed your issue, I apologize about that. I'm certainly not opposed to pull requests but I wonder how well `n x n` othello would fit into this crate. Currently bitboards are used to get all the extra performance necessary to perform deep tree searches. Right now the optimizations are pretty basic but I would like to use avx instructions in the future to boost performance even further. 

`n x n` boards would likely need some kind of data structure that will be harder to optimize in the same way. I think it could still be done relatively neatly from a user point of view where the crate special cases the classical `8 x 8 `. But considering that a generalization would involve pretty much a complete rewrite it might make more sense to write a new crate!

**Comment by LeoDog896** [comment]
> Hello! I completely missed your issue, I apologize about that. I'm certainly not opposed to pull requests but I wonder how well `n x n` othello would fit into this crate. Currently bitboards are used to get all the extra performance necessary to perform deep tree searches.

I see - thank you! I figured that `n x n` othello might be out of the scope of this crate, though I was unaware of the extent at which the crate was tied in to optimizations specifically for `8 x 8` othello.
